names= ['luffy', 'law', 'nami', 'sanji', 'zoro']
print(names[1])
print("dreams is what keeps folks living was once said by " + names[0].title()+ ".")
print("\t\n")
print("when destruction comes there needs to be " + names[1].title()+ ".")
print("\t\n")
print("when it rains, it pours just remain solid like " + names[2].title()+ "!")
print("\t\n")
print("A healthy system is required for a healthy life, a chef like " + names[3].title()+ "," "is needed")
print("\t\n")
print("I cannot allow myself to be ordinary was once said by, " + names[-1].title()+ ".")
print("t\n")
list= ['corvette', 'dodge', 'tesla', 'bmw']
print("I always found " + list[0].title()+ ", fascinating.")
print("\t\n")
print("As technology evolves " + list[2].title()+ ", will come in handy.")
print("\t\n")
ap= ['zombies', 'robots', 'aliens']
print(" one wouldn't invite " + ap[0].title()+ "," "because the zombie would eat humans")
print("\t\n")
print("The reason why " + ap[1].title()+ "," "is invited is because they can cook vegan food.")
print("\t\n")
print("Your're recieving this invation so the mad " + ap[-1].title()+ "," "won't invade us.")
print("\t\n")
ap[1] = 'lizards'
print(ap)
too_late= 'robots'
print("\n" + too_late.title() + " won't make it, due to technical difficulties.")
print(ap)
print("\t\n")
ap.insert(0, 'vampire')
ap.insert(3, 'shiba')
ap.append('doctor')
print(ap)
print("\t\n")
sorry_boss= ap.pop(0)
print("Sorry for the inconvenience " + sorry_boss.title() + ", but one tables won't arrive in time")
boss_= ap.pop(3)
print("\t\n" + boss_.title()+ ", sorry i am reaching out late but due to technical difficulties one table didn't arrive in time.")
del ap 
print(ap)